version: '3.8'
services:

  db:
    image: postgres:13
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: caeser
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge