version: '3.8'
services:

  caesar-db:
    container_name: caesar-db
    image: postgres:15.4-alpine3.18
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge